# Generated by Django 5.2.12 on 2026-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=16)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('admin', 'Admin'), ('api', 'API')], default='api', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('purpose', models.CharField(blank=True, max_length=16)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rooms_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rooms_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furnished', models.BooleanField(blank=True, null=True)),
                ('featured_only', models.BooleanField(default=False)),
                ('verified_owners_only', models.BooleanField(default=False)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('sort_by', models.CharField(choices=[('newest', 'Newest'), ('price_asc', 'Price ascending'), ('price_desc', 'Price descending'), ('relevance', 'Relevance'), ('distance', 'Distance')], default='newest', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
