# Generated by Codex

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_guest", models.BooleanField(default=True)),
                ("locale", models.CharField(default="uz", max_length=16)),
                ("current_path", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("last_seen_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "-created_at"],
            },
        ),
    ]
