import type { ListingDetail, ListingSummary, MapListingPreview } from "@/types/api";

export const fallbackListings: ListingSummary[] = [
  {
    id: 1,
    slug: "skyline-residence",
    title: "Skyline Residence With Private Terrace",
    purpose: "sale",
    category: "apartment",
    price: "420000",
    currency: "USD",
    city: { id: 1, name: "Tashkent", slug: "tashkent" },
    district: { id: 10, name: "Yunusabad", slug: "yunusabad" },
    latitude: "41.311081",
    longitude: "69.240562",
    rooms: 4,
    size_sqm: "185.00",
    is_featured: true,
    is_verified_owner: true,
    status: "active",
    moderation_status: "approved",
    owner_id: 1,
    owner_name: "Kamila Ismailova",
    images: [
      {
        id: 1,
        image_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        sort_order: 0,
        is_primary: true,
      },
    ],
    created_at: "2026-03-24T08:00:00Z",
    updated_at: "2026-03-24T08:00:00Z",
  },
  {
    id: 2,
    slug: "garden-court-villa",
    title: "Garden Court Villa Near International School",
    purpose: "sale",
    category: "house",
    price: "860000",
    currency: "USD",
    city: { id: 1, name: "Tashkent", slug: "tashkent" },
    district: { id: 12, name: "Mirzo-Ulugbek", slug: "mirzo-ulugbek" },
    latitude: "41.332500",
    longitude: "69.305000",
    rooms: 6,
    size_sqm: "410.00",
    is_featured: true,
    is_verified_owner: true,
    status: "active",
    moderation_status: "approved",
    owner_id: 2,
    owner_name: "Aziz Karimov",
    images: [
      {
        id: 2,
        image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        sort_order: 0,
        is_primary: true,
      },
    ],
    created_at: "2026-03-22T08:00:00Z",
    updated_at: "2026-03-22T08:00:00Z",
  },
  {
    id: 3,
    slug: "cobalt-business-loft",
    title: "Cobalt Business Loft For Boutique Office Use",
    purpose: "rent",
    category: "commercial",
    price: "4200",
    currency: "USD",
    city: { id: 1, name: "Tashkent", slug: "tashkent" },
    district: { id: 11, name: "Mirobod", slug: "mirobod" },
    latitude: "41.295200",
    longitude: "69.276100",
    rooms: null,
    size_sqm: "240.00",
    is_featured: false,
    is_verified_owner: true,
    status: "active",
    moderation_status: "approved",
    owner_id: 3,
    owner_name: "Javlon Khudoyberdiev",
    images: [
      {
        id: 3,
        image_url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
        sort_order: 0,
        is_primary: true,
      },
    ],
    created_at: "2026-03-20T08:00:00Z",
    updated_at: "2026-03-20T08:00:00Z",
  },
];

export const fallbackListingDetail: ListingDetail = {
  ...fallbackListings[0],
  description:
    "An elegant city residence with layered living spaces, oversized glazing, and a calm material palette designed for modern family life.",
  address: "Amir Temur Avenue 17, Tashkent",
  condition: "good",
  furnished: true,
  floor: 12,
  total_floors: 16,
  contact_phone: "+998 90 700 10 10",
  contact_whatsapp: "+998 90 700 10 10",
  contact_telegram: "@uytop_owner",
  allow_phone: true,
  allow_whatsapp: true,
  allow_telegram: true,
  view_count: 1842,
  published_at: "2026-03-21T08:00:00Z",
  expires_at: "2026-05-21T08:00:00Z",
  sold_or_rented_at: null,
  amenities: [
    { id: 1, title: "Parking", slug: "parking" },
    { id: 2, title: "Concierge", slug: "concierge" },
    { id: 3, title: "Terrace", slug: "terrace" },
  ],
  nearby_places: [
    { id: 1, place_type: "metro", title: "Bodomzor Metro", distance_meters: 450 },
    { id: 2, place_type: "school", title: "International School", distance_meters: 800 },
    { id: 3, place_type: "hospital", title: "Central Clinic", distance_meters: 1100 },
  ],
};

export const fallbackMapListings: MapListingPreview[] = fallbackListings.map((listing) => ({
  id: listing.id,
  slug: listing.slug,
  title: listing.title,
  purpose: listing.purpose,
  category: listing.category,
  price: listing.price,
  currency: listing.currency,
  city: listing.city.name,
  district: listing.district?.name ?? null,
  latitude: listing.latitude,
  longitude: listing.longitude,
  is_featured: listing.is_featured,
  is_verified_owner: listing.is_verified_owner,
  primary_image: listing.images[0]?.image_url ?? null,
}));
