# Generated by Django 5.2.12 on 2026-03-25 07:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('hero_image_url', models.URLField(blank=True, max_length=1000)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('trust_note', models.CharField(blank=True, max_length=320)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('sales_open', 'Sales open'), ('construction', 'Construction'), ('interior_finish', 'Interior finish'), ('ready', 'Ready')], default='sales_open', max_length=32)),
                ('handover', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_apartments', models.PositiveIntegerField(default=0)),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_to', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['project__name', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('apartment_number', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='draft', max_length=32)),
                ('is_public', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_apartments', to='locations.locationcity')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_apartments', to='locations.locationdistrict')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='catalog.projectbuilding')),
            ],
            options={
                'ordering': ['building__project__name', 'building__code', 'floor', 'apartment_number'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.apartment')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidentialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('headline', models.CharField(blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('delivery_window', models.CharField(blank=True, max_length=120)),
                ('hero_image_url', models.URLField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_projects', to='locations.locationcity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='catalog.developercompany')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_projects', to='locations.locationdistrict')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectbuilding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='catalog.residentialproject'),
        ),
        migrations.CreateModel(
            name='ApartmentPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('split_payment', 'Split payment')], max_length=32)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='catalog.apartment')),
            ],
            options={
                'ordering': ['payment_type'],
                'constraints': [models.UniqueConstraint(fields=('apartment', 'payment_type'), name='catalog_apartment_payment_type_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status', 'is_public'], name='catalog_apa_status_1cb8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['city', 'district'], name='catalog_apa_city_id_7e5903_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['price'], name='catalog_apa_price_0d5896_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['slug'], name='catalog_apa_slug_dddf8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('building', 'apartment_number'), name='catalog_apartment_building_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='residentialproject',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='catalog_project_company_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectbuilding',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='catalog_building_project_code_uniq'),
        ),
    ]
