# Generated by Django 5.2.12 on 2026-03-24 14:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=16)),
                ('category', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('needs_renovation', 'Needs renovation')], default='good', max_length=32)),
                ('furnished', models.BooleanField(default=False)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=32)),
                ('contact_telegram', models.CharField(blank=True, max_length=64)),
                ('allow_phone', models.BooleanField(default=True)),
                ('allow_whatsapp', models.BooleanField(default=False)),
                ('allow_telegram', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('sold', 'Sold'), ('rented', 'Rented')], default='draft', max_length=32)),
                ('moderation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified_owner', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sold_or_rented_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
