# Generated by Django 5.2.12 on 2026-03-24 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.locationcity'),
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.locationdistrict'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.amenity'),
        ),
        migrations.AddField(
            model_name='listingamenity',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(related_name='listings', through='listings.ListingAmenity', to='listings.amenity'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AddConstraint(
            model_name='listingamenity',
            constraint=models.UniqueConstraint(fields=('listing', 'amenity'), name='listings_listing_amenity_uniq'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'moderation_status', 'purpose', 'category'], name='listings_li_status_f07ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'district'], name='listings_li_city_id_6d4ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price', 'created_at'], name='listings_li_price_1355f9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['published_at'], name='listings_li_publish_32106c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured'], name='listings_li_is_feat_54dc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['slug'], name='listings_li_slug_a2fd83_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['view_count'], name='listings_li_view_co_ec1209_idx'),
        ),
    ]
